apiVersion: v1
kind: Pod
metadata:
 name: kaniko
spec:
 containers:
 - name: kaniko
   image: aisuko/kaniko-project-executor:latest
   args: ["--dockerfile={Dockerfile path}","--context=git://{user access token}@github.com/{repository}.git","--destination={docker hub user}/{repository}:{image tag}"] # replace with your dockerhub account
   volumeMounts:
     - name: kaniko-secret
       mountPath: /kaniko/.docker
 restartPolicy: Never
 volumes:
   - name: kaniko-secret
     secret:
       secretName: regcred
       items:
         - key: .dockerconfigjson
           path: config.json
