apiVersion: v1
kind: Pod
metadata:
 name: kaniko
spec:
 containers:
 - name: kaniko
   image: aisuko/kaniko-project-executor:latest
   args: ["--context=git://{user access token}@github.com{repository}.git","--dockerfile={Dockerfile path}","--destination={GCP repository}:{image tag}"] 
 restartPolicy: Never
